version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: "Install Sauce Connect Client"
          command: |
            sudo apt-get install lsof
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
      - run:
          name: "Launch Tunnel"
          background: true
          command: |
            cd sc-*
            bin/sc --pidfile /tmp/sc.pid1 -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -i demo-python-tunnel --no-remove-colliding-tunnels --se-port 4445
      - run:
          name: "Run Python Test"
          command: |
            while ! lsof -i:4445 -t; do sleep 3; done
            python on-boarding-modules/python-examples/test_module2.py
      - run:
          name: "Run PyTests"
          command: |
            pytest on-boarding-modules/pytest-examples/test_module2_pytest.py
            pytest on-boarding-modules/pytest-examples/test_module3_pytest.py
            pytest on-boarding-modules/pytest-examples/test_module4_pytest.py
      - run:
          name: "Run UnitTests"
          command: |
            python -m unittest on-boarding-modules/unittest-examples/*.py
#      - run:
#          name: "Run Appium-PyTests-Android-Realdevices"
#          command: |
#            cd appium-examples/pytest-realdevices/android
#            pytest -s -n 10 tests/
#      - run:
#          name: "Run Appium-PyTests-IOS-Realdevices"
#          command: |
#            cd appium-examples/pytest-realdevices/ios
#            pytest -s -n 10 tests/
      - run:
          name: "Run Appium IOS PyTests"
          command: |
            cd appium-examples/pytest-emusim/ios
            pytest -s -n 2 tests/
      - run:
          name: "Run Appium Android PyTests"
          command: |
            cd appium-examples/pytest-emusim/android
            pytest -s -n 2 tests/
      - run:
          name: "Shut Down Sauce Connect Tunnel"
          command: |
            kill -9 `cat /tmp/sc.pid1`
